apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-metauniv-front-deployment
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: dev-metauniv-front
  replicas: 4
  template:
    metadata:
      labels:
        app: dev-metauniv-front
    spec:
      containers:
      - name: dev-metauniv-front
        image: forargo.azurecr.io/web-front-server:v3
        ports:
        - containerPort: 80
